/* eslint-disable react-hooks/immutability */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/robotic-arm.glb -t -o src/components/RoboticArmClean.tsx 
*/

import * as THREE from 'three'
import React from 'react'
import { useFrame } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'
import { easing } from 'maath'

type ActionName = 'Animation'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_6: THREE.Mesh
    Object_8: THREE.Mesh
    Object_10: THREE.Mesh
    Object_12: THREE.Mesh
    Object_14: THREE.Mesh
    Object_16: THREE.Mesh
    Object_18: THREE.Mesh
    Object_20: THREE.Mesh
    Object_22: THREE.Mesh
    Object_24: THREE.Mesh
    Object_26: THREE.Mesh
    Object_28: THREE.Mesh
    Object_30: THREE.Mesh
    Object_32: THREE.Mesh
    Object_34: THREE.Mesh
    Object_36: THREE.Mesh
    Object_38: THREE.Mesh
    Object_40: THREE.Mesh
    Object_42: THREE.Mesh
    Object_44: THREE.Mesh
    Object_46: THREE.Mesh
    Object_48: THREE.Mesh
    Object_50: THREE.Mesh
    Object_52: THREE.Mesh
    Object_54: THREE.Mesh
    Object_56: THREE.Mesh
    Object_58: THREE.Mesh
    Object_60: THREE.Mesh
    Object_66: THREE.Mesh
    Object_68: THREE.Mesh
    Object_70: THREE.Mesh
    Object_72: THREE.Mesh
    Object_74: THREE.Mesh
    Object_76: THREE.Mesh
    Object_78: THREE.Mesh
    Object_80: THREE.Mesh
    Object_82: THREE.Mesh
    Object_84: THREE.Mesh
    Object_86: THREE.Mesh
    Object_88: THREE.Mesh
    Object_90: THREE.Mesh
    Object_92: THREE.Mesh
    Object_94: THREE.Mesh
    Object_96: THREE.Mesh
    Object_98: THREE.Mesh
    Object_100: THREE.Mesh
    Object_102: THREE.Mesh
    Object_104: THREE.Mesh
    Object_106: THREE.Mesh
    Object_108: THREE.Mesh
    Object_110: THREE.Mesh
    Object_112: THREE.Mesh
    Object_114: THREE.Mesh
    Object_116: THREE.Mesh
    Object_118: THREE.Mesh
    Object_120: THREE.Mesh
    Object_122: THREE.Mesh
    Object_126: THREE.Mesh
    Object_128: THREE.Mesh
    Object_130: THREE.Mesh
    Object_62: THREE.Mesh
    Object_64: THREE.Mesh
    Object_124: THREE.Mesh
  }
  materials: {
    robo_arm: THREE.MeshStandardMaterial
    robot_base: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: any) {
  const group = React.useRef<THREE.Group>(null)
  const robotCore = React.useRef<THREE.Group>(null)
  const { nodes, materials, animations } = useGLTF('/robotic-arm.glb') as any as GLTFResult
  const { actions } = useAnimations(animations, group)


  const scrubRef = React.useRef({ time: 0 })

  // Fluidly track the mouse cursor using a hybrid 2-Axis system
  useFrame((state, delta) => {
    if (robotCore.current && actions.Animation) {
      
      // 1. True Inverse-Kinematics Trigonometric Yaw (Left/Right)
      // Aggressive multiplier (2.5) for highly responsive tracking
      const targetYaw = Math.atan(state.pointer.x * 2.5)

      // 2. State-of-the-Art IK Arc-Compensation for Reach (Up/Down)
      const verticalReach = (state.pointer.y + 1) / 2
      const horizontalDepthRequirement = Math.abs(state.pointer.x) * 0.25
      
      const ikReach = verticalReach + horizontalDepthRequirement
      const normalizedReach = Math.min(Math.max(ikReach, 0), 1.0)
      
      const duration = actions.Animation.getClip().duration
      const targetTime = Math.max(0.01, Math.min(normalizedReach * duration, duration - 0.01))

      // Ultra-smooth horizontal rotation so it doesn't instantly snap (0.5s)
      easing.damp(robotCore.current.rotation, 'y', targetYaw, 0.5, delta);
      
      // Extremely heavy vertical damping (1.0s) to completely eliminate snapping on erratic up/down movements
      easing.damp(scrubRef.current, 'time', targetTime, 1.0, delta);

      // eslint-disable-next-line react-hooks/immutability
      actions.Animation.time = scrubRef.current.time
    }
  })

  // Setup the animation for manual scrubbing
  React.useEffect(() => {
    if (actions.Animation) {
      // OVERRIDE: Strip out any baked-in left/right sweeping from the original 3D artist's animation timeline.
      // This ensures that scrubbing the timeline (vertical mouse movement) strictly ONLY moves the arm up and down,
      // and doesn't trigger baked horizontal base rotations.
      const clip = actions.Animation.getClip();
      clip.tracks = clip.tracks.filter(track => {
        // Remove quaternion (rotation) tracks for the root/base nodes
        if (track.name.includes('quaternion')) {
          if (track.name.includes('Sketchfab_model') || 
              track.name.includes('root') || 
              track.name.includes('GLTF_SceneRootNode') ||
              track.name.includes('roboarm001_low_0')) {
            return false; // Drop this track to kill baked sweeping!
          }
        }
        return true;
      });

      actions.Animation.play()
      // Stop the mixer from advancing time automatically
      actions.Animation.setEffectiveTimeScale(0)
      
      // Stop the animation from ever looping mathematically
      actions.Animation.setLoop(THREE.LoopOnce, 1)
      // eslint-disable-next-line react-hooks/immutability
      actions.Animation.clampWhenFinished = true
    }
  }, [actions])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene" ref={robotCore}>
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="roboarm001_low_0" position={[0.217, 0.553, 0.307]} rotation={[-2.426, 0.528, 2.729]}>
                <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.robo_arm} />
              </group>
              <group name="roboarm002_low_1" position={[0.217, 0.553, 0.307]} rotation={[-2.426, 0.528, 2.729]}>
                <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials.robo_arm} />
              </group>
              <group name="roboarm003_low_2" position={[0.217, 0.553, 0.307]} rotation={[-2.426, 0.528, 2.729]}>
                <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.robo_arm} />
              </group>
              <group name="roboarm004_low_3" position={[0.217, 0.553, 0.307]} rotation={[-2.426, 0.528, 2.729]}>
                <mesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.robo_arm} />
              </group>
              <group name="roboarm005_low_4" position={[0.217, 0.553, 0.307]} rotation={[-2.426, 0.528, 2.729]}>
                <mesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials.robo_arm} />
              </group>
              <group name="roboarm006_low_5" position={[0.217, 0.553, 0.307]} rotation={[-2.426, 0.528, 2.729]}>
                <mesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials.robo_arm} />
              </group>
              <group name="roboarm007_low_6" position={[0.217, 0.553, 0.307]} rotation={[-2.426, 0.528, 2.729]}>
                <mesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials.robo_arm} />
              </group>
              <group name="roboarm008_low_7" position={[0.217, 0.553, 0.307]} rotation={[-2.426, 0.528, 2.729]}>
                <mesh name="Object_18" geometry={nodes.Object_18.geometry} material={materials.robo_arm} />
              </group>
              <group name="roboarm009_low_8" position={[0.217, 0.553, 0.307]} rotation={[-2.426, 0.528, 2.729]}>
                <mesh name="Object_20" geometry={nodes.Object_20.geometry} material={materials.robo_arm} />
              </group>
              <group name="roboarm010_low_9" position={[0.217, 0.553, 0.307]} rotation={[-2.426, 0.528, 2.729]}>
                <mesh name="Object_22" geometry={nodes.Object_22.geometry} material={materials.robo_arm} />
              </group>
              <group name="roboarm011_low_10" position={[0.217, 0.553, 0.307]} rotation={[-2.426, 0.528, 2.729]}>
                <mesh name="Object_24" geometry={nodes.Object_24.geometry} material={materials.robo_arm} />
              </group>
              <group name="roboarm012_low_11" position={[0.217, 0.553, 0.307]} rotation={[-2.426, 0.528, 2.729]}>
                <mesh name="Object_26" geometry={nodes.Object_26.geometry} material={materials.robo_arm} />
              </group>
              <group name="roboarm013_low_12" position={[0.217, 0.553, 0.307]} rotation={[-2.426, 0.528, 2.729]}>
                <mesh name="Object_28" geometry={nodes.Object_28.geometry} material={materials.robo_arm} />
              </group>
              <group name="roboarm014_low_13" position={[0.217, 0.553, 0.307]} rotation={[-2.426, 0.528, 2.729]}>
                <mesh name="Object_30" geometry={nodes.Object_30.geometry} material={materials.robo_arm} />
              </group>
              <group name="roboarm015_low_14" position={[0.217, 0.553, 0.307]} rotation={[-2.426, 0.528, 2.729]}>
                <mesh name="Object_32" geometry={nodes.Object_32.geometry} material={materials.robo_arm} />
              </group>
              <group name="roboarm016_low_15" position={[0.217, 0.553, 0.307]} rotation={[-2.426, 0.528, 2.729]}>
                <mesh name="Object_34" geometry={nodes.Object_34.geometry} material={materials.robo_arm} />
              </group>
              <group name="roboarm017_low_16" position={[0.217, 0.553, 0.307]} rotation={[-2.426, 0.528, 2.729]}>
                <mesh name="Object_36" geometry={nodes.Object_36.geometry} material={materials.robo_arm} />
              </group>
              <group name="roboarm018_low_17" position={[0.217, 0.553, 0.307]} rotation={[-2.426, 0.528, 2.729]}>
                <mesh name="Object_38" geometry={nodes.Object_38.geometry} material={materials.robo_arm} />
              </group>
              <group name="roboarm019_low_18" position={[0.217, 0.553, 0.307]} rotation={[-2.426, 0.528, 2.729]}>
                <mesh name="Object_40" geometry={nodes.Object_40.geometry} material={materials.robo_arm} />
              </group>
              <group name="roboarm020_low_19" position={[0.217, 0.553, 0.307]} rotation={[-2.426, 0.528, 2.729]}>
                <mesh name="Object_42" geometry={nodes.Object_42.geometry} material={materials.robo_arm} />
              </group>
              <group name="roboarm021_low_20" position={[0.217, 0.553, 0.307]} rotation={[-2.426, 0.528, 2.729]}>
                <mesh name="Object_44" geometry={nodes.Object_44.geometry} material={materials.robo_arm} />
              </group>
              <group name="roboarm022_low_21" position={[0.217, 0.553, 0.307]} rotation={[-2.426, 0.528, 2.729]}>
                <mesh name="Object_46" geometry={nodes.Object_46.geometry} material={materials.robo_arm} />
              </group>
              <group name="roboarm023_low_22" position={[0.217, 0.553, 0.307]} rotation={[-2.426, 0.528, 2.729]}>
                <mesh name="Object_48" geometry={nodes.Object_48.geometry} material={materials.robo_arm} />
              </group>
              <group name="roboarm024_low_23" position={[0.217, 0.553, 0.307]} rotation={[-2.426, 0.528, 2.729]}>
                <mesh name="Object_50" geometry={nodes.Object_50.geometry} material={materials.robo_arm} />
              </group>
              <group name="roboarm025_low_24" position={[0.217, 0.553, 0.307]} rotation={[-2.426, 0.528, 2.729]}>
                <mesh name="Object_52" geometry={nodes.Object_52.geometry} material={materials.robo_arm} />
              </group>
              <group name="roboarm026_low_25" position={[0.217, 0.553, 0.307]} rotation={[-2.426, 0.528, 2.729]}>
                <mesh name="Object_54" geometry={nodes.Object_54.geometry} material={materials.robo_arm} />
              </group>
              <group name="roboarm027_low_26" position={[0.217, 0.553, 0.307]} rotation={[-2.426, 0.528, 2.729]}>
                <mesh name="Object_56" geometry={nodes.Object_56.geometry} material={materials.robo_arm} />
              </group>
              <group name="roboarm028_low_27" position={[0.217, 0.553, 0.307]} rotation={[-2.426, 0.528, 2.729]}>
                <mesh name="Object_58" geometry={nodes.Object_58.geometry} material={materials.robo_arm} />
              </group>
              <group name="roboarm_low_28" position={[0.217, 0.553, 0.307]} rotation={[-2.426, 0.528, 2.729]}>
                <mesh name="Object_60" geometry={nodes.Object_60.geometry} material={materials.robo_arm} />
              </group>
              <group name="robot_base002_low_31" position={[0.092, 0.778, 0.038]} rotation={[-0.646, -0.553, 2.764]}>
                <mesh name="Object_66" geometry={nodes.Object_66.geometry} material={materials.robot_base} />
              </group>
              <group name="robot_base003_low_32" position={[0.121, 0.655, 0.154]} rotation={[-0.646, -0.553, 2.764]}>
                <mesh name="Object_68" geometry={nodes.Object_68.geometry} material={materials.robot_base} />
              </group>
              <group name="robot_base004_low_33" position={[0.079, 0.778, 0.028]} rotation={[-1.713, 0.109, 2.491]}>
                <mesh name="Object_70" geometry={nodes.Object_70.geometry} material={materials.robot_base} />
              </group>
              <group name="robot_base005_low_34" position={[0.126, 0.667, 0.148]} rotation={[-0.646, -0.553, 2.764]}>
                <mesh name="Object_72" geometry={nodes.Object_72.geometry} material={materials.robot_base} />
              </group>
              <group name="robot_base006_low_35" position={[0.146, 0.556, 0.248]} rotation={[-0.646, -0.553, 2.764]}>
                <mesh name="Object_74" geometry={nodes.Object_74.geometry} material={materials.robot_base} />
              </group>
              <group name="robot_base008_low_36" position={[0.436, 0.685, -0.343]} rotation={[2.132, 0.39, -2.597]}>
                <mesh name="Object_76" geometry={nodes.Object_76.geometry} material={materials.robot_base} />
              </group>
              <group name="robot_base009_low_37" position={[0.092, 0.258, 0.071]} rotation={[-Math.PI, 0.658, -Math.PI]}>
                <mesh name="Object_78" geometry={nodes.Object_78.geometry} material={materials.robot_base} />
              </group>
              <group name="robot_base018_low_38" position={[0, -0.001, 0]} rotation={[-Math.PI, 0.658, -Math.PI]}>
                <mesh name="Object_80" geometry={nodes.Object_80.geometry} material={materials.robot_base} />
              </group>
              <group name="robot_base011_low_39" position={[-0.124, 0.097, 0.16]} rotation={[2.132, 0.39, -2.597]}>
                <mesh name="Object_82" geometry={nodes.Object_82.geometry} material={materials.robot_base} />
              </group>
              <group name="robot_base012_low_40" position={[0.475, 2.037, -0.615]} rotation={[-0.646, -0.553, 2.764]}>
                <mesh name="Object_84" geometry={nodes.Object_84.geometry} material={materials.robot_base} />
              </group>
              <group name="robot_base013_low_41" position={[0.415, 0.685, -0.359]} rotation={[-1.713, 0.109, 2.491]}>
                <mesh name="Object_86" geometry={nodes.Object_86.geometry} material={materials.robot_base} />
              </group>
              <group name="robot_base014_low_42" position={[0.898, 0.517, -1.161]} rotation={[-1.713, 0.109, 2.491]}>
                <mesh name="Object_88" geometry={nodes.Object_88.geometry} material={materials.robot_base} />
              </group>
              <group name="robot_base015_low_43" position={[0.475, 2.037, -0.615]} rotation={[-0.646, -0.553, 2.764]}>
                <mesh name="Object_90" geometry={nodes.Object_90.geometry} material={materials.robot_base} />
              </group>
              <group name="robot_base016_low_44" position={[0.108, 0.258, 0.084]} rotation={[2.132, 0.39, -2.597]}>
                <mesh name="Object_92" geometry={nodes.Object_92.geometry} material={materials.robot_base} />
              </group>
              <group name="robot_base017_low_45" position={[-0.124, 0.097, 0.16]} rotation={[2.132, 0.39, -2.597]}>
                <mesh name="Object_94" geometry={nodes.Object_94.geometry} material={materials.robot_base} />
              </group>
              <group name="robot_base020_low_46" position={[0.898, 0.517, -1.161]} rotation={[-1.713, 0.109, 2.491]}>
                <mesh name="Object_96" geometry={nodes.Object_96.geometry} material={materials.robot_base} />
              </group>
              <group name="robot_base019_low_47" position={[-0.124, 0.097, 0.16]} rotation={[2.132, 0.39, -2.597]}>
                <mesh name="Object_98" geometry={nodes.Object_98.geometry} material={materials.robot_base} />
              </group>
              <group name="robot_base021_low_48" position={[-0.124, 0.097, 0.16]} rotation={[2.132, 0.39, -2.597]}>
                <mesh name="Object_100" geometry={nodes.Object_100.geometry} material={materials.robot_base} />
              </group>
              <group name="robot_base022_low_49" position={[-0.124, 0.097, 0.16]} rotation={[2.132, 0.39, -2.597]}>
                <mesh name="Object_102" geometry={nodes.Object_102.geometry} material={materials.robot_base} />
              </group>
              <group name="robot_base023_low_50" position={[-0.124, 0.097, 0.16]} rotation={[2.132, 0.39, -2.597]}>
                <mesh name="Object_104" geometry={nodes.Object_104.geometry} material={materials.robot_base} />
              </group>
              <group name="robot_base_low_51" position={[0.898, 0.517, -1.161]} rotation={[-1.713, 0.109, 2.491]}>
                <mesh name="Object_106" geometry={nodes.Object_106.geometry} material={materials.robot_base} />
              </group>
              <group name="robot_base024_low_52" position={[-0.124, 0.097, 0.16]} rotation={[2.132, 0.39, -2.597]}>
                <mesh name="Object_108" geometry={nodes.Object_108.geometry} material={materials.robot_base} />
              </group>
              <group name="robot_base025_low_53" position={[0, -0.001, 0]} rotation={[-Math.PI, 0.658, -Math.PI]}>
                <mesh name="Object_110" geometry={nodes.Object_110.geometry} material={materials.robot_base} />
              </group>
              <group name="robot_base026_low_54" position={[0.898, 0.517, -1.161]} rotation={[-1.713, 0.109, 2.491]}>
                <mesh name="Object_112" geometry={nodes.Object_112.geometry} material={materials.robot_base} />
              </group>
              <group name="robot_base027_low_55" position={[0.475, 2.037, -0.615]} rotation={[-0.646, -0.553, 2.764]}>
                <mesh name="Object_114" geometry={nodes.Object_114.geometry} material={materials.robot_base} />
              </group>
              <group name="robot_base028_low_56" position={[0.898, 0.517, -1.161]} rotation={[-1.713, 0.109, 2.491]}>
                <mesh name="Object_116" geometry={nodes.Object_116.geometry} material={materials.robot_base} />
              </group>
              <group name="robot_base029_low_57" position={[-0.124, 0.097, 0.16]} rotation={[2.132, 0.39, -2.597]}>
                <mesh name="Object_118" geometry={nodes.Object_118.geometry} material={materials.robot_base} />
              </group>
              <group name="robot_base030_low_58" position={[-0.124, 0.097, 0.16]} rotation={[2.132, 0.39, -2.597]}>
                <mesh name="Object_120" geometry={nodes.Object_120.geometry} material={materials.robot_base} />
              </group>
              <group name="robot_base031_low_59" position={[0, -0.001, 0]} rotation={[-Math.PI, 0.658, -Math.PI]}>
                <mesh name="Object_122" geometry={nodes.Object_122.geometry} material={materials.robot_base} />
              </group>
              <group name="robot_base007_low_61" position={[0.146, 0.556, 0.248]} rotation={[-2.426, 0.528, 2.729]}>
                <mesh name="Object_126" geometry={nodes.Object_126.geometry} material={materials.robot_base} />
              </group>
              <group name="robot_base033_low_62" position={[0.618, 0.687, -0.204]} rotation={[2.132, 0.39, -2.597]} scale={1.085}>
                <mesh name="Object_128" geometry={nodes.Object_128.geometry} material={materials.robot_base} />
              </group>
              <group name="robot_base035_low_63" position={[0.898, 0.517, -1.161]} rotation={[-1.713, 0.109, 2.491]}>
                <mesh name="Object_130" geometry={nodes.Object_130.geometry} material={materials.robot_base} />
              </group>
              <group name="robot_base010_low_29" position={[0, 0.074, 0]}>
                <mesh name="Object_62" geometry={nodes.Object_62.geometry} material={materials.robot_base} />
              </group>
              <group name="robot_base001_low_30" position={[0, -0.001, 0]}>
                <mesh name="Object_64" geometry={nodes.Object_64.geometry} material={materials.robot_base} />
              </group>
              <group name="robot_base032_low_60" position={[0, -0.001, 0]}>
                <mesh name="Object_124" geometry={nodes.Object_124.geometry} material={materials.robot_base} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/robotic-arm.glb')
